final List<Map<String, dynamic>> questions = [
  {
    'image': 'assets/images/letter&numbers/letters/أسد.png',
    'word': 'أسد',
    'options': ['أ', 'ت', 'ط'],
    'correct_answer': 'أ',
  },
  {
    'image': 'assets/images/letter&numbers/letters/بيت.png',
    'word': 'بيت',
    'options': ['ب', 'ن', 'ك'],
    'correct_answer': 'ب',
  },
  {
    'image': 'assets/images/letter&numbers/letters/تاج.png',
    'word': 'تاج',
    'options': ['ت', 'ص', 'ق'],
    'correct_answer': 'ت',
  },
  {
    'image': 'assets/images/letter&numbers/letters/ثعلب.png',
    'word': 'ثعلب',
    'options': ['ث', 'د', 'ح'],
    'correct_answer': 'ث',
  },
  {
    'image': 'assets/images/letter&numbers/letters/جزر.png',
    'word': 'جزر',
    'options': ['ج', 'ز', 'ر'],
    'correct_answer': 'ج',
  },
  {
    'image': 'assets/images/letter&numbers/letters/حقيبة.png',
    'word': 'حقيبة',
    'options': ['ح', 'خ', 'م'],
    'correct_answer': 'ح',
  },
  {
    'image': 'assets/images/letter&numbers/letters/خروف.png',
    'word': 'خروف',
    'options': ['خ', 'غ', 'ش'],
    'correct_answer': 'خ',
  },
  {
    'image': 'assets/images/letter&numbers/letters/دب.png',
    'word': 'دب',
    'options': ['د', 'ذ', 'ز'],
    'correct_answer': 'د',
  },
  {
    'image': 'assets/images/letter&numbers/letters/ذره.png',
    'word': 'ذره',
    'options': ['ذ', 'د', 'ز'],
    'correct_answer': 'ذ',
  },
  {
    'image': 'assets/images/letter&numbers/letters/رمان.png',
    'word': 'رمان',
    'options': ['ر', 'ز', 'د'],
    'correct_answer': 'ر',
  },
  {
    'image': 'assets/images/letter&numbers/letters/زرافة.png',
    'word': 'زرافة',
    'options': ['ز', 'س', 'ذ'],
    'correct_answer': 'ز',
  },
  {
    'image': 'assets/images/letter&numbers/letters/سيارة.png',
    'word': 'سيارة',
    'options': ['س', 'ش', 'ص'],
    'correct_answer': 'س',
  },
  {
    'image': 'assets/images/letter&numbers/letters/شمس.png',
    'word': 'شمس',
    'options': ['ش', 'س', 'ص'],
    'correct_answer': 'ش',
  },
  {
    'image': 'assets/images/letter&numbers/letters/ضفدع.png',
    'word': 'ضفدع',
    'options': ['ض', 'ص', 'ف'],
    'correct_answer': 'ض',
  },
  {
    'image': 'assets/images/letter&numbers/letters/صاروخ.png',
    'word': 'صاروخ',
    'options': ['ص', 'س', 'ط'],
    'correct_answer': 'ص',
  },
  {
    'image': 'assets/images/letter&numbers/letters/طائرة.png',
    'word': 'طائرة',
    'options': ['ط', 'ش', 'ص'],
    'correct_answer': 'ط',
  },
  {
    'image': 'assets/images/letter&numbers/letters/ظفر.png',
    'word': 'ظفر',
    'options': ['ظ', 'ض', 'ف'],
    'correct_answer': 'ظ',
  },
  {
    'image': 'assets/images/letter&numbers/letters/عين.png',
    'word': 'عين',
    'options': ['ع', 'غ', 'ف'],
    'correct_answer': 'ع',
  },
  {
    'image': 'assets/images/letter&numbers/letters/غواصة.png',
    'word': 'غواصة',
    'options': ['غ', 'غ', 'غ'],
    'correct_answer': 'غ',
  },
  {
    'image': 'assets/images/letter&numbers/letters/فراشة.png',
    'word': 'فراشة',
    'options': ['ف', 'م', 'ق'],
    'correct_answer': 'ف',
  },
  {
    'image': 'assets/images/letter&numbers/letters/قلم.png',
    'word': 'قلم',
    'options': ['ق', 'و', 'ص'],
    'correct_answer': 'ق',
  },
  {
    'image': 'assets/images/letter&numbers/letters/كرسي.png',
    'word': 'كرسي',
    'options': ['ك', 'ن', 'ش'],
    'correct_answer': 'ك',
  },
  {
    'image': 'assets/images/letter&numbers/letters/ليمون.png',
    'word': 'ليمون',
    'options': ['ل', 'ن', 'م'],
    'correct_answer': 'ل',
  },
  {
    'image': 'assets/images/letter&numbers/letters/موز.png',
    'word': 'موز',
    'options': ['م', 'ز', 'و'],
    'correct_answer': 'م',
  },
  {
    'image': 'assets/images/letter&numbers/letters/نحلة.png',
    'word': 'نحلة',
    'options': ['ن', 'ر', 'ق'],
    'correct_answer': 'ن',
  },
  {
    'image': 'assets/images/letter&numbers/letters/ولد.png',
    'word': 'ولد',
    'options': ['و', 'ز', 'ص'],
    'correct_answer': 'و',
  },
  {
    'image': 'assets/images/letter&numbers/letters/هدهد.png',
    'word': 'هدهد',
    'options': ['ه', 'ح', 'خ'],
    'correct_answer': 'ه',
  },
  {
    'image': 'assets/images/letter&numbers/letters/يد.png',
    'word': 'يد',
    'options': ['ي', 'ك', 'م'],
    'correct_answer': 'ي',
  },
];
