// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU05nKfToWCk42BgR7-GSOmi2nE6P85z8',
    appId: '1:1068047963456:web:6039e7f5b5dd347939d6a5',
    messagingSenderId: '1068047963456',
    projectId: 'kide-app-83399',
    authDomain: 'kide-app-83399.firebaseapp.com',
    storageBucket: 'kide-app-83399.firebasestorage.app',
    measurementId: 'G-925VD4VR9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMZSmt0UqC30HwJhm7-uHvNGhjDGpBe0',
    appId: '1:1068047963456:android:d4051d953ae2387739d6a5',
    messagingSenderId: '1068047963456',
    projectId: 'kide-app-83399',
    storageBucket: 'kide-app-83399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdUXpAxf0IhgtZxqVk-YPSos7WIsWRC7o',
    appId: '1:1068047963456:ios:7da209dd209d740639d6a5',
    messagingSenderId: '1068047963456',
    projectId: 'kide-app-83399',
    storageBucket: 'kide-app-83399.firebasestorage.app',
    iosBundleId: 'com.example.test0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdUXpAxf0IhgtZxqVk-YPSos7WIsWRC7o',
    appId: '1:1068047963456:ios:7da209dd209d740639d6a5',
    messagingSenderId: '1068047963456',
    projectId: 'kide-app-83399',
    storageBucket: 'kide-app-83399.firebasestorage.app',
    iosBundleId: 'com.example.test0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU05nKfToWCk42BgR7-GSOmi2nE6P85z8',
    appId: '1:1068047963456:web:1b9757baaed8b0e539d6a5',
    messagingSenderId: '1068047963456',
    projectId: 'kide-app-83399',
    authDomain: 'kide-app-83399.firebaseapp.com',
    storageBucket: 'kide-app-83399.firebasestorage.app',
    measurementId: 'G-ZRWD92XL3M',
  );
}
